### ISSUE TITLE
Lazyness induced `NullPointerException`

### ISSUE THREAD

**Issue by JustusAdam** [typelead/eta#564] opened 2017-11-20 16:25 UTC
Without `deepseq` -ing this code 

```hs
generateBindingWith (Binding prefix) = OhuaM $ do
        taken <- use $ nameGenerator . takenNames
        let a = map (T.pack . show) ([0..] :: [Int])
        -- deepseqM (take 10 a)
        let (h:_) = dropWhile (`HS.member` taken) $ map (Binding . (prefix' <>)) a
        nameGenerator . takenNames %= HS.insert h
        pure h
```

(from this [file](https://github.com/ohua-dev/ohua-core/blob/master/src/Ohua/Internal/Monad.hs#L68))
Causes a `NullPointerException` in the `let a =` line.

```
Exception in thread "main" eta.runtime.exception.EtaException: JException java.lang.NullPointerException
        at ohua_core.ohua.internal.Monad$sat_s2LKX.apply1(Monad.hs:70)
        at base.ghc.Base$sat_sAH6.thunkEnter(Base.hs:851)
        at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:18)
        at ohua_core.ohua.internal.Monad$sat_s2LLT.apply1(Monad.hs:72)
        at base.ghc.List$dropWhile.apply2(List.hs:534)
        at ohua_core.ohua.internal.Monad$h_s2LL2.thunkEnter(Monad.hs:70)
        at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:18)
        at text.data.text.Show$sat_s3KOH.thunkEnter(Show.hs:42)
        at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:18)
        at base.ghc.Base$zpzp.apply2(Base.hs:904)
        at base.ghc.Base$sat_sAHM.thunkEnter(Base.hs:798)
        at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:18)
        at base.ghc.io.handle.Text$$wa7.enter(Text.hs:586)
        at base.ghc.io.handle.Text$hPutStr2.apply3V(Text.hs:553)
        at main.Main$main1.applyV(NPEBug.hs:7)
        at main.Main$DZCmain.applyV(NPEBug.hs)
        at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:104)
        at eta.runtime.stg.Capability.schedule(Capability.java:157)
        at eta.runtime.stg.Capability.scheduleClosure(Capability.java:102)
        at eta.runtime.Runtime.evalLazyIO(Runtime.java:189)
        at eta.runtime.Runtime.main(Runtime.java:182)
        at eta.main.main(Unknown Source)
```

### Reproduce

- clone `ohua-dev/ohua-core` on the `npe-bug` branch
- `etlas build` (using a sandbox sandbox is recommended, an appropriate `cabal.config` file is present) and `etlas exec npe-bug`

the main file is `misc/NPEBug.hs`

**Comment by rahulmutt** [comment] 2017-12-01 17:20
Thanks for reporting this! I was able to reproduce it on the current master. Let me know if this is blocking you w/o a workaround and I'll make it a priority. Otherwise, I'll take a look when we start a round of bug fixes.

**Comment by JustusAdam** [comment] 2017-12-02 01:08
Its not blocking currently, as including a single `deepseq` (I wonder if a `seq` would perhaps suffice) is enough to make it work. This workaround has no measurable influence right now so its fine. But I'd appreciate being updated if there are new developments on this front ;)

**Comment by rahulmutt** [comment] 2017-12-18 15:11
This seems to be fixed as of https://github.com/typelead/eta/commit/8a3f0f66579fdf3c21d5868593d1aeef8eb1a552. I will do a release and close this issue once a binary release is out.

**Comment by JustusAdam** [comment] 2017-12-18 16:17
Once the release is out I can test if it works and then close the issue if you like.

**Comment by rahulmutt** [comment] 2018-01-04 21:02
@JustusAdam Just did a binary release for Eta v0.7 which should have the fix above. Please test it out and close this issue if it's fixed.

**Comment by rahulmutt** [comment] 2018-02-14 09:03
Closing this as it should most likely be fixed. If you encounter a similar bug again, feel free to file a new issue.

**Closed by rahulmutt** 2018-02-14 09:03 UTC
Labels: bug

**Comment by JustusAdam** [comment] 2018-02-14 10:39
Yeah, sorry I didn't get around to testing it. But I did revert the workaround I added so I should run into it if its still there.
