### ISSUE TITLE
Errors related with decoding functions in Network.HTTP.Types

### ISSUE THREAD

**Issue by jneira** [typelead/eta#320] opened 2017-04-25 04:27 UTC
Hi, in the tests of wai-servlet i've got a pair of errors in the package Network.HTTP.Types:

* With this code:
```haskell
print $ Network.HTTP.Types.parseQuery "a=1&b=2"
````
the error is
```
Exception in thread "main" java.lang.NullPointerException
        at eta.runtime.io.MemoryManager.getAddress(MemoryManager.java:61)
        at http_types.network.http.types.URI$nzusYCZZ.thunkEnter(Unknown Source)
        at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
        at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
        at http_types.network.http.types.URI$dszusYEH.thunkEnter(Unknown Source)
        at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
        at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
        at http_types.network.http.types.URI$satzusYF8.thunkEnter(Unknown Source)
        at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
        at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
        at bytestring.data.bytestring.Internal$unpackChars.enter(Unknown Source)
        at main.Main$satzusCXT.thunkEnter(Unknown Source)
        at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
        at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
        at base.ghc.io.handle.Text$zdwa7.enter(Unknown Source)
        at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
        at main.Main$main1.enter(Unknown Source)
        at eta.runtime.apply.StgFun.apply(StgFun.java:19)
        at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
        at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
        at main.Main$main30.enter(Unknown Source)
        at main.Main$DZCmain.enter(Unknown Source)
        at eta.runtime.apply.StgFun.apply(StgFun.java:19)
        at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
        at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
        at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
        at eta.runtime.stg.Capability.schedule(Capability.java:260)
        at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
        at eta.runtime.Rts.evalLazyIO(Rts.java:95)
        at eta.runtime.Rts.hsMain(Rts.java:38)
        at eta.main.main(Unknown Source)
```
* With 
```haskell
print $ Network.HTTP.Types.decodePathSegments "/my/path"
```
the stacktrace is:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkIndex(Unknown Source)
        at java.nio.HeapByteBuffer.getShort(Unknown Source)
        at text.data.text.Show$zdwunfoldzus3MXV.enter(Unknown Source)
        at text.data.text.Show$satzus3MY6.thunkEnter(Unknown Source)
        at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
        at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
        at base.ghc.Show$showLitString.enter(Unknown Source)
        at base.ghc.Show$satzusW8B.thunkEnter(Unknown Source)
        at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
        at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
        at base.ghc.io.handle.Text$zdwa7.enter(Unknown Source)
        at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
        at main.Main$main1.enter(Unknown Source)
        at eta.runtime.apply.StgFun.apply(StgFun.java:19)
        at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
        at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)
        at main.Main$main29.enter(Unknown Source)
        at main.Main$DZCmain.enter(Unknown Source)
        at eta.runtime.apply.StgFun.apply(StgFun.java:19)
        at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
        at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
        at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
        at eta.runtime.stg.Capability.schedule(Capability.java:260)
        at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
        at eta.runtime.Rts.evalLazyIO(Rts.java:95)
        at eta.runtime.Rts.hsMain(Rts.java:38)
        at eta.main.main(Unknown Source)
```

**Comment by rahulmutt** [comment] 2017-04-25 07:37
I wonder if this happened as a result of the recent change in the behaviour of `nullAddr`?

**Comment by jneira** [comment] 2017-04-25 08:38
The first one it is clearly related; i am not sure about the second, maybe it is caused if you try to do a `getShort` over `MemoryManager.nullAddress`.
Anyway i dont understand why nullAddr# is involved if it is handling informed strings 😕

**Comment by rahulmutt** [comment] 2017-04-25 13:08
I just grepped the bytestring patch for `null`'s and I found one:
https://github.com/typelead/eta-hackage/blob/master/patches/bytestring-0.10.8.1.patch#L499

I can't imagine why `null` would even be a return value for that. I'll check it out.

**Comment by rahulmutt** [comment] 2017-04-25 16:01
So it turns out replacing `null` with `MemoryManager.nullAddress` fixes the problem (there was a null check). Without the change you did, it would've given the same exception - just that no one has tickled it yet. See https://github.com/typelead/eta-hackage/commit/ef3b5af6626947e540c4c9126f495a1a6059d9c3

**Comment by rahulmutt** [comment] 2017-04-25 16:39
The second bug I was able to reduce even further to this:

```haskell
decodeWithUtf8 lenientDecode "SomeBytestring"
```

This is present in the helper function `decodePathSegment` and if I replace `decodeWithUtf8 lenientDecode` with `decodeUtf8` it works. Looks like something we need to fix in the [text patch](https://github.com/typelead/eta-hackage/blob/master/patches/text-1.2.2.1.patch).

**Comment by jneira** [comment] 2017-04-26 12:50
good hunting! i've tested that the change in bytestring fixes the `print $ Network.HTTP.Types.parseQuery` 
i'll try to take a look to text package bug

**Comment by jneira** [comment] 2017-04-27 08:57
Mmm in my last tests `print $ decodeUtf8 "SomeBytestring"` fails with the same error too (with last version of eta,etlas and pakages)
It's a little bit difficult for me to trace the execution of decodeWithUtf8... 😕

**Comment by jneira** [comment] 2017-04-27 09:50
* IMO the more suspicious code should be the java foreign import in `eta.text.Utils.decode_utf8`, cause haskell code in text package is supposed to work with ghc . So i 've added some debug in the java method
* with this test:
```haskell
 print $ decodeUtf8 "SomeBytestring"
```
* and this change in text package (java/Utils.java):
```java
public static ByteBuffer decode_utf8( StgByteArray destArray, ByteBuffer destOffset
                                        , ByteBuffer src,  ByteBuffer srcend) {
        /* TODO: This part of the text implementation can be optimized.
                 Unnecessary byte buffers are being created. Instead,
                 we can change the implementation at the Eta level
                 itself. */
        ByteBuffer state0 = allocateAnonymousBuffer(4, false);
        bufPutInt(state0, 0, UTF8_ACCEPT);
        ByteBuffer codepoint0 = allocateAnonymousBuffer(4, false);
        ByteBuffer src0 = allocateAnonymousBuffer(4, false);
        bufPutInt(src0, 0, getAddress(src));
        debug("Dest array: "+destArray+", destOffset: "+destOffset+
              ", src: "+src+", srcend: "+srcend);
        ByteBuffer ret = decode_utf8_int(destArray.buf, destOffset,
                                         src0, srcend, codepoint0, state0);
        debug("src0: "+src0+", codepoint0: "+codepoint0+
              ", state0: "+state0+", ret: "+ret);
        if (bufGetInt(state0, 0) != UTF8_ACCEPT) {
            debug("State != UTF8_ACCEPT: "+bufGetInt(state0, 0));
            bufSetOffset(ret, -1);
        }
        debug("Ret: "+ret);
        return ret;
    }
```
* it outputs:
```
Dest array: eta.runtime.io.StgByteArray@35bcd2, destOffset: java.nio.DirectByteB
uffer[pos=4 lim=8 cap=8], src: java.nio.DirectByteBuffer[pos=4 lim=18 cap=18], s
rcend: java.nio.DirectByteBuffer[pos=18 lim=18 cap=18]
src0: java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], codepoint0: java.nio.HeapByteB
uffer[pos=0 lim=8 cap=8], state0: java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], re
t: java.nio.DirectByteBuffer[pos=18 lim=18 cap=18]
Ret: java.nio.DirectByteBuffer[pos=18 lim=18 cap=18]
Exception in thread "main" java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkIndex(Unknown Source)
        at java.nio.HeapByteBuffer.getShort(Unknown Source)
        at text.data.text.Show$zdwunfoldzus2PP9.enter(Unknown Source)
        at text.data.text.Show$satzus2PPK.thunkEnter(Unknown Source)
        at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
        at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
        at base.ghc.Show$showLitString.enter(Unknown Source)
        at base.ghc.Show$satzusW8B.thunkEnter(Unknown Source)
        at eta.runtime.thunk.StgInd.enter(StgInd.java:12)
        at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
        at base.ghc.io.handle.Text$zdwa7.enter(Unknown Source)
        at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
        at main.Main$main1.enter(Unknown Source)
        at eta.runtime.apply.StgFun.apply(StgFun.java:19)
        at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
        at eta.runtime.exception.StgException$Catch.enter(StgException.java:194)

        at main.Main$main5.enter(Unknown Source)
        at main.Main$DZCmain.enter(Unknown Source)
        at eta.runtime.apply.StgFun.apply(StgFun.java:19)
        at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
        at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
        at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
        at eta.runtime.stg.Capability.schedule(Capability.java:260)
        at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
        at eta.runtime.Rts.evalLazyIO(Rts.java:96)
        at eta.runtime.Rts.hsMain(Rts.java:38)
        at eta.main.main(Unknown Source)
```
* the result is the ByteBuffer with the content of the decoding, do you see some anomally in it?

**Comment by rahulmutt** [comment] 2017-04-27 09:57
I think decodeUtf8 itself is fine. The problem seems to be in the `unpack` function.

Here's the trace I got the other day: https://gist.github.com/rahulmutt/78275924d036088559e96ae98ab9c1c6

The code was:
```haskell
main = seq (length (T.unpack $ decodeUtf8With strictDecode y)) $ print "Hello"
```

**Comment by rahulmutt** [comment] 2017-04-27 10:11
The problem is here:
[main] INFO text.data.text.Internal$TextD - << Internal$TextD(1=eta.runtime.io.StgByteArray@6f8e9d06, 2=0, 3=14)

The `Text` is being created with length of 14, but it only has length 7. There's some doubling happening that shouldn't be. It makes sense why it is trying to index past the end of the Text.

**Comment by rahulmutt** [comment] 2017-04-27 10:29
Found it. In `decode_utf8_int`, `destOffset` should be set as follows:

```java
        bufPutInt(destOffset, 0, (d.position() - dest.position()) / 2);
```
instead of
```
        bufPutInt(destOffset, 0, d.position() - dest.position());
```

because `destOffset` should be measured in 16-bit units. Verifying now.

**Comment by rahulmutt** [comment] 2017-04-27 10:41
Seems to be working now - `etlas update` and try again?

**Comment by rahulmutt** [comment] 2017-04-28 13:30
Seems to be fixed, closing.

**Closed by rahulmutt** 2017-04-28 13:30 UTC
Labels: bug

**Comment by jneira** [comment] 2017-05-01 19:12
yeah, i can show the entire wai request now, thanks!
