### ISSUE TITLE
[eta-tour]: Bug - hello world type program produces no output

### ISSUE THREAD

**Issue by jstr045329** [typelead/eta#748] opened 2018-05-21 22:14 UTC
The following code produces no output in the console:

Source Code:
```haskell
main :: IO ()
main = do

  putStrLn "Interact with me!"
```

Output:
```shell
```

[write-further-description-here]

**Comment by rahulmutt** [comment] 2018-05-22 04:46
@jstr045329 I am unable to reproduce this. Maybe it was a transient error on the backend side. Are you seeing any errors in the console?

**Comment by rahulmutt** [comment] 2018-06-20 00:47
Closing, as the bug was not reproducible.

**Closed by rahulmutt** 2018-06-20 00:47 UTC
