### ISSUE TITLE
Trying to get an invite for eta-lang.slack.com leads to an error on hamsterpad.com

### ISSUE THREAD

**Issue by filippovitale** [typelead/eta#226] opened 2017-02-14 13:48 UTC
![eta-slack](https://cloud.githubusercontent.com/assets/773288/22931354/4c5e3418-f292-11e6-8722-ad33f65ebfd4.gif)

**Comment by rahulmutt** [comment] 2017-02-14 14:01
I tried it on Mac OS X El Capitan with both Safari & Chrome and when I click the 'Get My Invite' button, it'll take me to a form where I can create a HamsterPad account.

Can you share the details of your OS/Browser and which region you're accessing from?

Is anyone else able to reproduce this?

**Comment by filippovitale** [comment] 2017-02-14 14:17
> when I click the 'Get My Invite' button, it'll take me to a form where I can create a HamsterPad account

For me too. I didn't capture in the GIF the account creation. After you create an account you then get the error:

![c4kwycixaaamvb2 jpg-](https://cloud.githubusercontent.com/assets/773288/22932566/5fcfc738-f296-11e6-96b0-99d04a97562b.jpg)

**Comment by filippovitale** [comment] 2017-02-14 14:21
I am using an hamsterpad account made with my @gmail.com address... could that be the problem?

<img width="558" alt="screen shot 2017-02-14 at 9 18 20 am" src="https://cloud.githubusercontent.com/assets/773288/22932711/eafac2fe-f296-11e6-8b6d-5bb2ddfa43d1.png">

**Comment by rahulmutt** [comment] 2017-02-14 14:36
We have lots of people on the Slack channel right now that don't have email addresses in those domains. We'll try removing that setting and see if that helps. 

@Jyothsnasrinivas Can you take a look?

**Comment by Jyothsnasrinivas** [comment] 2017-02-14 15:25
I removed the domains. @filippovitale can you please check now? Make sure you are signing up with the same email you used to sign up for Slack.
 
https://www.hamsterpad.com/chat/eta-lang

**Comment by filippovitale** [comment] 2017-02-14 16:21
Sorry @Jyothsnasrinivas , same problem.

BTW you removed the `@typelead.com` and `@rediff.com` domains. It looks like that right now only email addresses from `@google.com` are allowed to create an account for: https://eta-lang.slack.com/

**Comment by Jyothsnasrinivas** [comment] 2017-02-14 16:30
Ok. @filippovitale Are you using the same email for Slack and Hamsterpad? And, are you currently on other Slack channels?

**Comment by filippovitale** [comment] 2017-02-14 18:15
Yes, and yes

**Comment by Jyothsnasrinivas** [comment] 2017-02-15 04:43
Ok. @filippovitale I'll notify the Hamsterpad guys regarding this. Others are able to join without any issues. Meanwhile, can you please personal message me your email on Gitter? I'll send you a direct invite to the Eta Slack Channel.

**Comment by Jyothsnasrinivas** [comment] 2017-02-17 17:46
Currently we are unable to reproduce this. Since we manually added you, I'm closing this issue.

**Closed by Jyothsnasrinivas** 2017-02-17 17:46 UTC
Labels: website
