### ISSUE TITLE
epm install binary fails (Installation depends on ordering)

### ISSUE THREAD

**Issue by psibi** [typelead/eta#87] opened 2016-10-18 20:36 UTC
Have a fresh `ghcvm` installation with just the base packages:

```
sibi::casey { ~ }-> ghcvm-pkg list
/home/sibi/.ghcvm/package.conf.d
   base-4.8.2.0
   ghc-prim-0.4.0.0
   integer-0.5.1.0
   rts-0.1.0.0
```

Then, do a `cabalvm install binary`:

```
sibi::casey { ~ }-> cabalvm install binary
Resolving dependencies...
Found patch in ghcvm-hackage for array-0.5.1.1
Initialized empty Git repository in /tmp/cabal-tmp-32191/array-0.5.1.1/.git/
Configuring array-0.5.1.1...
Configuring array-0.5.1.1...
Building array-0.5.1.1...
Building array-0.5.1.1...
Preprocessing library array-0.5.1.1...
[ 1 of 15] Compiling Data.Array.Base  ( Data/Array/Base.hs, dist/build/Data/Array/Base.jar )
[ 2 of 15] Compiling Data.Array.MArray ( Data/Array/MArray.hs, dist/build/Data/Array/MArray.jar )
[ 3 of 15] Compiling Data.Array.MArray.Safe ( Data/Array/MArray/Safe.hs, dist/build/Data/Array/MArray/Safe.jar )
[ 4 of 15] Compiling Data.Array.IO.Internals ( Data/Array/IO/Internals.hs, dist/build/Data/Array/IO/Internals.jar )
[ 5 of 15] Compiling Data.Array.IO    ( Data/Array/IO.hs, dist/build/Data/Array/IO.jar )
[ 6 of 15] Compiling Data.Array.IO.Safe ( Data/Array/IO/Safe.hs, dist/build/Data/Array/IO/Safe.jar )
[ 7 of 15] Compiling Data.Array.ST    ( Data/Array/ST.hs, dist/build/Data/Array/ST.jar )
[ 8 of 15] Compiling Data.Array.ST.Safe ( Data/Array/ST/Safe.hs, dist/build/Data/Array/ST/Safe.jar )
[ 9 of 15] Compiling Data.Array.Storable.Internals ( Data/Array/Storable/Internals.hs, dist/build/Data/Array/Storable/Internals.jar )
[10 of 15] Compiling Data.Array.Storable ( Data/Array/Storable.hs, dist/build/Data/Array/Storable.jar )
[11 of 15] Compiling Data.Array.Storable.Safe ( Data/Array/Storable/Safe.hs, dist/build/Data/Array/Storable/Safe.jar )
[12 of 15] Compiling Data.Array.Unsafe ( Data/Array/Unsafe.hs, dist/build/Data/Array/Unsafe.jar )
[13 of 15] Compiling Data.Array       ( Data/Array.hs, dist/build/Data/Array.jar )
[14 of 15] Compiling Data.Array.IArray ( Data/Array/IArray.hs, dist/build/Data/Array/IArray.jar )
[15 of 15] Compiling Data.Array.Unboxed ( Data/Array/Unboxed.hs, dist/build/Data/Array/Unboxed.jar )
Linking dist/build/HSarray-0.5.1.1.jar ...
In-place registering array-0.5.1.1...
Creating package registration file:
/tmp/pkgConf-array-0.5.17833686901102520059.1
Installing library in
/home/sibi/.cabalvm/lib/x86_64-linux-ghcvm-0.0.1-ghc7_10_3/array-0.5.1.1
Registering array-0.5.1.1...
Installed array-0.5.1.1
Configuring deepseq-1.4.2.0...
Configuring deepseq-1.4.2.0...
Building deepseq-1.4.2.0...
Building deepseq-1.4.2.0...
Preprocessing library deepseq-1.4.2.0...
[1 of 1] Compiling Control.DeepSeq  ( Control/DeepSeq.hs, dist/build/Control/DeepSeq.jar )
Linking dist/build/HSdeepseq-1.4.2.0.jar ...
In-place registering deepseq-1.4.2.0...
Creating package registration file:
/tmp/pkgConf-deepseq-1.4.219374770841827336327.0
Installing library in
/home/sibi/.cabalvm/lib/x86_64-linux-ghcvm-0.0.1-ghc7_10_3/deepseq-1.4.2.0
Registering deepseq-1.4.2.0...
Installed deepseq-1.4.2.0
Found patch in ghcvm-hackage for bytestring-0.10.8.1
Found patch in ghcvm-hackage for containers-0.5.8.1
Initialized empty Git repository in /tmp/cabal-tmp-32191/bytestring-0.10.8.1/.git/
Initialized empty Git repository in /tmp/cabal-tmp-32192/containers-0.5.8.1/.git/
Configuring containers-0.5.8.1...
Configuring containers-0.5.8.1...
Configuring bytestring-0.10.8.1...
Configuring bytestring-0.10.8.1...
Building containers-0.5.8.1...
cabalvm: Run the 'configure' command first.
```

**Comment by psibi** [comment] 2016-10-18 20:40
If I manually install `containers` first and then install `binary`- it works. But that's not how it should be, I think.

**Comment by rahulmutt** [comment] 2016-10-19 04:25
It looks like it happens when running concurrent builds. If I can confirm it, I'll temporarily disable concurrent builds and work on a fix at a later time.

**Comment by psibi** [comment] 2016-12-24 21:37
This issue has been solved via: https://github.com/typelead/epm/commit/d36ea97976dceb345264a48572340860128f33a8

But let's keep this issue open until we restore concurrent builds and fix this problem in a more proper manner.

**Comment by rahulmutt** [comment] 2017-04-11 04:30
Closing, we have concurrent builds in `etlas` now.

**Closed by rahulmutt** 2017-04-11 04:30 UTC
Labels: bug
