### ISSUE TITLE
Build time error msg -- eta.exe: panic! (the 'impossible' happened)

### ISSUE THREAD

**Issue by indegro** [typelead/eta#587] opened 2017-12-14 10:53 UTC
I tried to use eta with hlint package to write custom processor.
And got build error -- 

> Building binary-0.8.5.1...
Failed to install binary-0.8.5.1
Build log ( C:\Users\ddushyn\AppData\Roaming\etlas\logs\eta-0.0.9.6\binary-0.8.5.1-XCulyUW0jLDfM8QjWWONO.log ):
Preprocessing library for binary-0.8.5.1..
Building library for binary-0.8.5.1..
eta.exe: panic! (the 'impossible' happened)
  (Eta version 0.0.9b6):
        Cannot parse #if directive in file src/Data/Binary/Get/Internal.hs  at line 64 col 1:
    end of input

Cabal file 

> name:                etlas-hlint-example
version:             0.1.0.0
-- synopsis:
-- description:
license:             BSD3
license-file:        LICENSE
author:              Test Test
maintainer:          test.test@test.com
-- copyright:
-- category:
build-type:          Simple
extra-source-files:  ChangeLog.md
cabal-version:       >=1.10
library
  -- exposed-modules:
  -- other-modules:
  -- other-extensions:
  build-depends:       base >=4.8 && <4.9,
                       hlint
  hs-source-dirs:      src
  default-language:    Haskell2010

I am a total newbie to Eta/Etlas and have the following questions

1.  How can I get more verbose output ?
2.  What can I do to resolve that problem ? 
3.  Are there somes workaround? (I know it depends on 1/2 questions)

Thanks

**Comment by rahulmutt** [comment] 2017-12-15 05:21
To get more verbose output, you can add a `-v3` flag.

Can you upload your full project on github so I can reproduce? Moreover, which version of `eta` are you using (`etlas exec eta -- --version`)?

**Comment by indegro** [comment] 2017-12-15 13:21
I copies project to repository 
https://github.com/indegro/eta-with-hlint

`etlas exec eta -- --version`
>  `Compiler for the Eta Programming Language, version 0.0.9b6`

**Comment by indegro** [comment] 2017-12-15 13:36
I have found at the moment that etlas could not compile process library

> Resolving dependencies...
Found patch in eta-hackage for process-1.6.2.0
Configuring process-1.6.2.0...
Building process-1.6.2.0...
Failed to install process-1.6.2.0
Build log ( C:\Users\ddushyn\AppData\Roaming\etlas\logs\eta-0.0.9.6\process-1.6.2.0-BfZhYw6AMJMKqIaPw2vYzO.log ):
Preprocessing library for process-1.6.2.0..
Building library for process-1.6.2.0..
[1 of 5] Compiling System.Process.Common ( System\Process\Common.hs, dist\build\System\Process\Common.jar )
_**System\Process\Common.hs:206:24: Not in scope: `FD.fdPath'**_
etlas: Leaving directory 'C:\Users\ddushyn\AppData\Local\Temp\etlas-tmp-18148\process-1.6.2.0'
etlas: Error: some packages failed to install:
process-1.6.2.0-BfZhYw6AMJMKqIaPw2vYzO failed during the building phase. The
exception was:
ExitFailure 1

**Comment by rahulmutt** [comment] 2017-12-16 04:47
Right, because there is a change in the `base` library needed to make it work. Can you try out the latest Docker image or install the `master` version with source?

**Comment by rahulmutt** [comment] 2018-01-05 08:27
@indegro Just did a binary release for Eta v0.7 which should have the fix above. Please test it out and close this issue if it's fixed. You can run `etlas select --latest` to get the new version.

**Closed by rahulmutt** 2018-01-05 08:27 UTC

**Comment by indegro** [comment] 2018-01-05 09:32
Hello @rahulmutt .
Sorry for late response. 
I just updated etlas and eta version as you recommened and found the following errors

> Failed to install extra-1.6.2
 Build log ( C:\Users\ddushyn\AppData\Roaming\etlas\logs\eta-0.7.0.1\extra-1.6.2-BGvXahguXVDB3TUcwFAqx9.log ):
Preprocessing library for extra-1.6.2..
Building library for extra-1.6.2..
src\System\Directory\Extra.hs:32:18:
    Could not find module 'System.Posix'
    Use -v to see a list of the files searched for.
etlas: Leaving directory 'C:\Users\ddushyn\AppData\Local\Temp\etlas-tmp-3604\extra-1.6.2'


It could not find System.Posix module

**Comment by rahulmutt** [comment] 2018-01-06 11:51
@indegro I just pushed a patch for `extra-1.6.2` - turns out they added FFI calls in the new version because `1.5.*` was working before. Please file new issues for any additional errors you have.
