### ISSUE TITLE
Add new case for foreign exports: allow generic type parameter as result 

### ISSUE THREAD

**Issue by jneira** [typelead/eta#892] opened 2018-10-25 07:29 UTC
## Description

I've tried to define a foreign export with this shape:

```haskell
foreign export java "@static org.dhall.eta.Input.withType" jinput
  :: (ja <: Object) => JInputType ja -> JString -> IO ja
jinput jty = undefined
``` 
(same behaviour replacing `IO ja` with `Java x ja`, being x a free variable or a bound one) 
## Expected Behavior
The compiler should generate a java method like:
```java
public class Input {
  public static <A> A withType(InputType<A> ty, String s) {
   ..... 
  }
}
```

## Actual Behavior
Eta throws a compile error:
```
Building library for dhall-eta-0.1.0..
 Compiling Dhall.Eta
 src\main\eta\Dhall\Eta.hs:45:1:  error:
    Unacceptable result type in foreign declaration:
      ‘ja’ is not a data type
    When checking declaration:
      foreign export java "@static org.dhall.eta.Input.withType" jinput
        :: (ja <: Object) => JInputType ja -> JString -> IO ja
 foreign export java "@static org.dhall.eta.withType" jinput
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Possible Fix
Add the case to foreign exports

## Context
Implementing exports to wrap `dhall-haskell` in https://github.com/eta-lang/dhall-eta/blob/java-types/src/main/eta/Dhall/Eta.hs#L45-L47

## Your Environment

* Did you install an older version of Eta/Etlas before? 
  * Yes
* Current Eta & Etlas version:
  * Both built by myself from master versions
* Operating System and version:
  * Windows 10
* Link to your project:
  * https://github.com/eta-lang/dhall-eta/tree/java-types

**Comment by jneira** [comment] 2018-10-25 07:54
As a workaround i have to wrap the type paremter in a dummy wrapper:
```haskell
data JIdentity a = JIdentity (@org.haskell.types.Identity a)
   deriving (Class,Show,Eq)

foreign import java unsafe "@new" newIdentity  :: (a <: Object)
                                               => a -> JIdentity a

foreign import java unsafe "get" jrunIdentity :: (a <: Object)
                                              => JIdentity a -> a

instance Class a => JavaConverter (Identity a) (JIdentity a) where
  toJava = newIdentity . runIdentity
  fromJava = pure . jrunIdentity

foreign export java "@static org.dhall.eta.Input.withType" jinput
  :: (ja <: Object) => JInputType ja -> JString -> IO (JIdentity ja)
jinput jty = fmap newIdentity . input (fromJava jty)
```

**Comment by rahulmutt** [comment] 2018-10-25 07:56
Great to see a workaround. I think making your original example compile is just relaxing the checks in the foreign export typechecking code.

**Comment by jneira** [comment] 2018-10-26 08:10
It seems the workaround compiles but fails at runtime:

```haskell
testIdentity :: (a <: Object) => a -> JIdentity a
testIdentity a = newIdentity a

foreign export java "@static org.dhall.eta.Types.test" testIdentity
  :: (a <: Object) => a -> JIdentity a
```
The call 
```java
Identity<String> test = Types.test("hola");
``` 
fails with
```
Exception in thread "main" java.lang.ClassCastException: eta.runtime.apply.PAP1_1 cannot be cast to dhall_eta.eta.types.datacons.JIdentity
	at org.dhall.eta.Types.test(Unknown Source)
	at org.dhall.eta.example.Client.main(Client.java:75)
```

**Comment by rahulmutt** [comment] 2018-10-26 12:33
Thanks for testing @jneira! That looks like a bug. It should be fixed as the original issue is worked on as well.

**Comment by jneira** [comment] 2018-10-29 09:14
@rahulmutt  I would like to try fix this one but i didn't know in deep the guts for typecheck and codegen foreign exports, could you give me some guidance? :sweat_smile:

**Comment by jneira** [comment] 2018-10-29 12:48
With #893 compiler accepts the signature and now i have the runtime error mentioned above:
```
Exception in thread "main" java.lang.ClassCastException: eta.runtime.apply.PAPSlow cannot be cast to ghc_prim.ghc.types.datacons.Ozh
        at eta.example.Foreign.test(Unknown Source)
        at Utils.main(Utils.java:23)
```

**Comment by rahulmutt** [comment] 2018-10-29 13:03
That was quick! :)

And yes, the code generation bit needs to be tweaked now. I recall making some conservative assumptions about the structure of an foreign export, so those assumptions will be relaxed to handle the more sophisticated exports.

The relevant code is here:

https://github.com/typelead/eta/blob/master/compiler/Eta/DeSugar/DsForeign.hs#L620-L785

It's not very pretty so let me know if you want me to provide some context. The fastest way to get an overall feel for what it's trying to do is to decompile the exported classes in your `dhall-eta` project.

**Comment by rahulmutt** [comment] 2018-10-29 13:04
In particular, I think the assumption we made was that the result type of a foreign export would *not* be polymorphic, so we'll need to think through how the code generation will look like in that case.

**Comment by jneira** [comment] 2018-10-29 13:09
Thanks a lot, i'll take a look to the code

**Comment by rahulmutt** [comment] 2018-10-29 14:48
Ok I understand now why you get PAP errors - a PAP is a curried function.

So the current code generation code was structured to run Java/IO actions that do not have any extends constraints:
```
foreign export java "@static org.dhall.eta.Types.test" testIdentity
  :: (a <: Object) => a -> JIdentity a
```
So in this example, only the code generated will supply the `a` argument, but not the `a <: Object` argument. All typeclass constraints end up being real arguments that must be passed to the function. So what's happening is that just one argument is being passed so the runtime sees that one more argument is required so it returns a PAP instead of running the function.

The code generation must account for the extends constraints.

**Comment by rahulmutt** [comment] 2018-11-02 10:02
@jneira Have you tried some exports in `dhall-eta` and see if it works as intended with your recent patch?

**Comment by jneira** [comment] 2018-11-02 22:55
@rahulmutt Yeah, the simple use cases in `dhall-eta` works now
```haskell
input :: forall ja. (Class ja) => JType ja -> JString -> IO ja
input jty = dhallInput (fromJava jty)

foreign export java "@static org.dhall.eta.Input.type" input
  :: (ja <: Object) => JType ja -> JString -> IO ja
```

**Comment by rahulmutt** [comment] 2018-11-03 02:55
Ok great! Closing.

**Closed by rahulmutt** 2018-11-03 02:55 UTC
Labels: ffi
