### ISSUE TITLE
Can't run jar even in uberjar-mode

### ISSUE THREAD

**Issue by JulianZhang** [typelead/eta#324] opened 2017-04-26 02:52 UTC
I had install eta  0.0.6b3

But can't run jar even in uberjar mode the error info is as blow.

I had try etlas run without uberjar-mode, the error info is the same.

```
$etlas clean
cleaning...
$ etlas configure --enable-uberjar-mode
Resolving dependencies...
Configuring eta-example-0.1.0.0...
zhangjuns-MacBook-Pro:eta-example zhangjun$ etlas build
Preprocessing executable 'eta-example' for eta-example-0.1.0.0..
Building executable 'eta-example' for eta-example-0.1.0.0..
[1 of 1] Compiling Main             ( src/Main.hs, dist/build/eta-example/eta-example-tmp/Main.jar )

src/Main.hs:10:1: Warning: Tab character

src/Main.hs:11:1: Warning: Tab character

src/Main.hs:12:1: Warning: Tab character

src/Main.hs:15:5: Warning: Tab character

src/Main.hs:16:5: Warning: Tab character

src/Main.hs:17:5: Warning: Tab character

src/Main.hs:18:5: Warning: Tab character

src/Main.hs:19:5: Warning: Tab character

src/Main.hs:26:1: Warning: Tab character
Linking dist/build/eta-example/eta-example.jar ...

$ java -jar ./dist/build/eta-example/eta-example.jar
Exception in thread "main" java.lang.NoClassDefFoundError: eta/base/Utils
	at base.system.Environment$getArgs1.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StgContext.checkForStackFrames(StgContext.java:79)
	at base.ghc.Base$bindIO1.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:260)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:96)
	at eta.runtime.Rts.hsMain(Rts.java:38)
	at eta.main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: eta.base.Utils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
```

**Comment by JulianZhang** [comment] 2017-04-26 03:14
I had install 0.0.6b2 before, I'm not sure does the problem related with the old version.

**Comment by rahulmutt** [comment] 2017-04-26 03:50
Unable to reproduce (on 0.0.6b3). Can you manually delete the `dist` directory in your project and try building again? Also share the file listing of the jar file `eta-example.jar`.

**Comment by JulianZhang** [comment] 2017-04-26 05:18
@rahulmutt I had manually delete the dist directory  and build again. The error is the same, and you can see the file list on the link [filelist](https://gist.github.com/JulianZhang/aff72514004626ea6a15212bff760912)

**Comment by JulianZhang** [comment] 2017-04-26 05:39
@rahulmutt I remove the dl4j from project, to make you easy to check the problem. The new info is in the  [link](https://gist.github.com/JulianZhang/6326ba4077807d2dd1fe8ddb30d554af)

**Comment by rahulmutt** [comment] 2017-04-26 05:54
Can you upload your project somewhere (github works) so I can clone and run your exact configuration?

**Comment by JulianZhang** [comment] 2017-04-26 06:14
@rahulmutt I had upload it to  https://github.com/JulianZhang/eta-example

**Comment by JulianZhang** [comment] 2017-04-27 03:20
@rahulmutt  my platform is macOS, I had try even the example can't run either.

```
 $eta HelloWorld.hs
[1 of 1] Compiling Main             ( HelloWorld.hs, HelloWorld.jar )
Linking RunHelloWorld.jar ...
$ ls
HelloWorld.hi		HelloWorld.jar		Lens.hs
HelloWorld.hs		JavaGenerics.hs		RunHelloWorld.jar
$ java -jar RunHelloWorld.jar
Exception in thread "main" java.lang.NoClassDefFoundError: eta/base/Utils
	at base.ghc.io.encoding.Iconv$zdLrFTUMlvl.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
	at base.ghc.io.encoding.Iconv$localeEncodingName.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgIndStatic.enter(StgIndStatic.java:27)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at base.ghc.io.Encoding$getFileSystemEncodingzugo.enter(Unknown Source)
	at base.ghc.io.Encoding$getFileSystemEncoding5.enter(Unknown Source)
	at base.ghc.io.Encoding$initLocaleEncoding1.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
	at base.ghc.io.Encoding$initLocaleEncoding.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgIndStatic.enter(StgIndStatic.java:27)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at base.ghc.io.handle.Internals$mkDuplexHandle7.enter(Unknown Source)
	at base.ghc.io.handle.FD$zdLrI9PBlvl4.enter(Unknown Source)
	at eta.runtime.apply.StgFun.apply(StgFun.java:19)
	at eta.runtime.apply.Apply$ApVFast.enter(Apply.java:42)
	at base.ghc.IO$unsafeDupablePerformIO.enter(Unknown Source)
	at base.ghc.io.handle.FD$stdout.thunkEnter(Unknown Source)
	at eta.runtime.thunk.StgIndStatic.enter(StgIndStatic.java:27)
	at eta.runtime.stg.StgClosure.evaluate(StgClosure.java:23)
	at base.ghc.io.handle.Internals$wantWritableHandle1.enter(Unknown Source)
	at base.ghc.io.handle.Text$hPutStr2.enter(Unknown Source)
	at base.ghc.io.handle.Text$hPutStrLn1.enter(Unknown Source)
	at base.system.IO$putStrLn1.enter(Unknown Source)
	at base.system.IO$putStrLn.enter(Unknown Source)
	at eta.runtime.apply.Apply$PAPApply.enter(Apply.java:231)
	at eta.runtime.apply.StgPAP.apply(StgPAP.java:46)
	at eta.runtime.apply.ApV.stackEnter(ApV.java:12)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:43)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.StackFrame.enter(StackFrame.java:26)
	at eta.runtime.stg.Capability.schedule(Capability.java:260)
	at eta.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57)
	at eta.runtime.Rts.evalLazyIO(Rts.java:96)
	at eta.runtime.Rts.hsMain(Rts.java:38)
	at eta.main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: eta.base.Utils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
```

**Comment by rahulmutt** [comment] 2017-04-27 03:21
Can you try wiping of `~/.eta`, `~/.etlas`, and running`./cleaninstall.sh` in the cloned repo?

**Comment by JulianZhang** [comment] 2017-04-27 03:53
@rahulmutt After delete ~/.eta , ~/.etlas and then run install with cleaninstall.sh, I run eta again to create RunHelloWorld.jar. But the error is the same, the [link](https://gist.github.com/JulianZhang/93fb6b1d6c0bfbf6c099b199a2415d37) is file list for the  RunHelloWorld.jar

**Comment by rahulmutt** [comment] 2017-04-27 04:04
Can you share the directory structure & file sizes of `libraries/base/dist`?

**Comment by JulianZhang** [comment] 2017-04-27 06:30
@rahulmutt   the [link](https://gist.github.com/JulianZhang/ee3b212483503121459549bf7c805a9d) is file list and file size

**Comment by JulianZhang** [comment] 2017-04-27 07:54
@rahulmutt I had try build 0.0.6b3 on centOS, I can run hello world . I had diff the libraries/base/dist with my macOS, the  `build/__extras.jar` is missing on my mac.

and the diff about file size is in the [link](https://gist.github.com/JulianZhang/0512421fd9d81921c9d68bb67ac1565a)

**Comment by rahulmutt** [comment] 2017-04-27 08:03
Hmm that explains the `eta/base/Utils` missing because that will be in `build/__extras.jar`.

Can you go to `libraries/base` and run this command:

`shake/Build.hs`, can you change
```haskell
      installFlags = ["--allow-boot-library-installs"]
```
to
```haskell
      installFlags = ["--allow-boot-library-installs","-v3"]
```
then run `./cleaninstall.sh` and share the output?

**Comment by JulianZhang** [comment] 2017-04-27 08:21
@rahulmutt  I had change the flags and run install again. output is blow

install.log and .etlas/logs/eta-0.0.6/base-4.8.2.0-IPFDtZjmEfh5tPXF10v5hF.log in the [link](https://gist.github.com/JulianZhang/345c0f1d5c91c672cdc4c78981d09963)
```
 ./cleaninstall.sh  > install.log
Cabal file warning in /Users/zhangjun/code/haskell/eta/etlas/etlas/etlas.cabal: Ignoring unknown section type: custom-setup
Cabal file warning in /Users/zhangjun/code/haskell/eta/etlas/etlas/etlas.cabal: Ignoring unknown section type: custom-setup

Copying from /Users/zhangjun/code/haskell/eta/.stack-work/install/x86_64-osx/lts-6.27/7.10.3/bin/eta to /Users/zhangjun/.local/bin/eta
Copying from /Users/zhangjun/code/haskell/eta/.stack-work/install/x86_64-osx/lts-6.27/7.10.3/bin/eta-build to /Users/zhangjun/.local/bin/eta-build
Copying from /Users/zhangjun/code/haskell/eta/.stack-work/install/x86_64-osx/lts-6.27/7.10.3/bin/eta-pkg to /Users/zhangjun/.local/bin/eta-pkg
Copying from /Users/zhangjun/code/haskell/eta/.stack-work/install/x86_64-osx/lts-6.27/7.10.3/bin/etlas to /Users/zhangjun/.local/bin/etlas
Copying from /Users/zhangjun/code/haskell/eta/.stack-work/install/x86_64-osx/lts-6.27/7.10.3/bin/example to /Users/zhangjun/.local/bin/example

Copied executables to /Users/zhangjun/.local/bin:
- eta
- eta-build
- eta-pkg
- etlas
- example



Warning: cannot determine version of /opt/local/bin/strip :
""
Warning: solver failed to find a solution:
Could not resolve dependencies:
next goal: ghc-prim (user goal)
rejecting: ghc-prim-0.4.0.0 (only already installed instances can be used)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: ghc-prim
Trying configure anyway.
Warning: cannot determine version of /opt/local/bin/strip :
""
Warning: cannot determine version of /opt/local/bin/strip :
""
Warning: solver failed to find a solution:
Could not resolve dependencies:
next goal: base (user goal)
rejecting: base-4.8.2.0 (only already installed instances can be used)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base
Trying configure anyway.
Warning: cannot determine version of /opt/local/bin/strip :
""


```

**Comment by rahulmutt** [comment] 2017-04-28 15:59
In `libraries/base/java-utils`, can you run the following commands:
```
/usr/bin/javac -cp '/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/ghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE/HSghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE.jar:/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/integer-0.5.1.0-ACyqTmAMUMGGvisLFeQbAm/HSinteger-0.5.1.0-ACyqTmAMUMGGvisLFeQbAm.jar:/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/rts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w/HSrts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w.jar' Utils.java
```
and
```
/usr/bin/javac -cp '/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/ghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE/HSghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE.jar:/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/integer-0.5.1.0-ACyqTmAMUMGGvisLFeQbAm/HSinteger-0.5.1.0-ACyqTmAMUMGGvisLFeQbAm.jar:/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/rts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w/HSrts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w.jar' HSIConv.java
```
And share what happens?

**Comment by JulianZhang** [comment] 2017-04-29 08:23
@rahulmutt After 1st command the Utils.class was created.

The 2nd command failed, error info is blow
The class Utils can't been find when compile the HSIConv.java.

I had try to add `/Users/zhangjun/code/haskell/eta/libraries/base/java-utils/` or `/Users/zhangjun/code/haskell/eta/libraries/base/java-utils/Utils.class` to classpath but the error info didn't change.
```
$ /usr/bin/javac -cp '/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/ghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE/HSghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE.jar:/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/integer-0.5.1.0-ACyqTmAMUMGGvisLFeQbAm/HSinteger-0.5.1.0-ACyqTmAMUMGGvisLFeQbAm.jar:/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/rts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w/HSrts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w.jar' HSIConv.java
HSIConv.java:13: 错误: 找不到符号
import eta.base.Utils;
               ^
  符号:   类 Utils
  位置: 程序包 eta.base
HSIConv.java:43: 错误: 找不到符号
			String fromEncodingStr=Utils.byteBufferToStr(fromEncoding);
			                       ^
  符号:   变量 Utils
  位置: 类 HSIConv
HSIConv.java:45: 错误: 找不到符号
			String toEncodingStr=Utils.byteBufferToStr(toEncoding);
			                     ^


  符号:   变量 Utils
  位置: 类 HSIConv
HSIConv.java:157: 错误: 找不到符号
					Utils.set_errno(E2BIG);
					^
  符号:   变量 Utils
  位置: 类 HSIConv
HSIConv.java:159: 错误: 找不到符号
					Utils.set_errno(EILSEQ);
					^
  符号:   变量 Utils
  位置: 类 HSIConv
HSIConv.java:167: 错误: 找不到符号
			Utils.set_errno(EILSEQ);
			^
  符号:   变量 Utils
  位置: 类 HSIConv
6 个错误
```

My default java info is blow
```
$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
$ javac -version
javac 1.8.0_66
```

**Comment by rahulmutt** [comment] 2017-04-29 08:26
My bad, the command should be:
```
/usr/bin/javac -cp '/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/ghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE/HSghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE.jar:/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/integer-0.5.1.0-ACyqTmAMUMGGvisLFeQbAm/HSinteger-0.5.1.0-ACyqTmAMUMGGvisLFeQbAm.jar:/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/rts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w/HSrts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w.jar' Utils.java HSIConv.java
```

**Comment by JulianZhang** [comment] 2017-04-29 08:29
@rahulmutt  both class file create now
```
$ /usr/bin/javac -cp '/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/ghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE/HSghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE.jar:/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/integer-0.5.1.0-ACyqTmAMUMGGvisLFeQbAm/HSinteger-0.5.1.0-ACyqTmAMUMGGvisLFeQbAm.jar:/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/rts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w/HSrts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w.jar' Utils.java HSIConv.java
$ ls -l
total 72
-rw-r--r--  1 zhangjun  staff  5658  4 29 16:28 HSIConv.class
-rw-r--r--  1 zhangjun  staff  5795  4 27 13:36 HSIConv.java
-rw-r--r--  1 zhangjun  staff  7350  4 29 16:28 Utils.class
-rw-r--r--  1 zhangjun  staff  8612  4 27 13:36 Utils.java
```

**Comment by rahulmutt** [comment] 2017-04-29 10:11
Now in that folder, can you try 

```
eta -cp '/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/ghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE/HSghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE.jar:/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/integer-0.5.1.0-ACyqTmAMUMGGvisLFeQbAm/HSinteger-0.5.1.0-ACyqTmAMUMGGvisLFeQbAm.jar:/Users/zhangjun/.etlas/lib/x86_64-osx-eta-0.0.6-ghc7_10_3/rts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w/HSrts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w.jar' HSIConv.java Utils.java
```

If it's working correctly, there should be an `__extras.jar` that's generated.

**Comment by JulianZhang** [comment] 2017-04-29 11:09
@rahulmutt after command a new Run.jar was created.

But I didn't find  `__extras.jar`, I had check  `libraries/base/java-utils/` and `libraries/base/dist/build` .

I had check with my ubuntu , another file `libraries/integer/dist/build/__extras.jar` didn't find on mac.

**Comment by rahulmutt** [comment] 2017-05-11 16:54
@JulianZhang Any updates on this? Does this still happen after doing `./cleaninstall.sh` on master?

**Comment by JulianZhang** [comment] 2017-05-12 08:20
@rahulmutt I had run ./update.sh and ./cleaninstall.sh on my mac, the problem is the same.

Can't find __extras.jar in libraries/, and the RunHelloWorld.jar can't run by java -jar.

Still can't eta.base.Utils class.

**Comment by rahulmutt** [comment] 2017-05-13 06:09
@JulianZhang Are you able to reproduce `https://github.com/typelead/eta-hackage/issues/36`?

**Comment by JulianZhang** [comment] 2017-05-13 13:02
@rahulmutt Yes, The problem it the same. as I said before, the two __extras.jar file are missing on macOS

 etlas install bytestring-0.10.8.1
Warning: The package list for 'etlas.typelead.com' is 16 days old.
Run 'etlas update' to get the latest list of available packages.
Resolving dependencies...
Found patch in eta-hackage for bytestring-0.10.8.1
Configuring bytestring-0.10.8.1...
Building bytestring-0.10.8.1...
Failed to install bytestring-0.10.8.1
Build log ( /Users/zhangjun/.etlas/logs/eta-0.0.6/bytestring-0.10.8.1-BfpZ30g0iJ8LZqZyX72dzK.log ):
etlas: Entering directory '/var/folders/dt/m9kwylpd01v3qh5qlj6dnxch0000gq/T/etlas-tmp-5310/bytestring-0.10.8.1'
Configuring bytestring-0.10.8.1...
Preprocessing library for bytestring-0.10.8.1..
Building library for bytestring-0.10.8.1..
java/Utils.java:188: 错误: 程序包eta.integer不存在
            x = eta.integer.Utils.divideUnsigned(x, 10);
                           ^
1 个错误

etlas: Leaving directory '/var/folders/dt/m9kwylpd01v3qh5qlj6dnxch0000gq/T/etlas-tmp-5310/bytestring-0.10.8.1'
etlas: Error: some packages failed to install:
bytestring-0.10.8.1-BfpZ30g0iJ8LZqZyX72dzK failed during the building phase.
The exception was:
ExitFailure 1

**Comment by ChinaXing** [comment] 2017-05-14 12:30
so, the issue fixed ? @rahulmutt

**Comment by rahulmutt** [comment] 2017-05-14 15:00
This function:
```haskell
compileFiles :: HscEnv -> Phase -> [(String, Maybe Phase)] -> IO [FilePath]
compileFiles hsc_env stop_phase srcs = do
  o_files' <- mapM (compileFile hsc_env stop_phase) non_java_srcs
  let dflags' = foldr addClassPaths (hsc_dflags hsc_env)
              $ class_dirs
              ++ o_files'
      classesDir = fromMaybe "." (objectDir dflags') </> "classes"
  genClassPaths <- if (not (null java_source_srcs))
                   then do
                     createDirectoryIfMissing True classesDir
                     runJavac dflags' $ ["-d", classesDir] ++ java_source_srcs
                   else return []
  extras <- getOutputFilename StopLn Persistent "__extras" dflags' StopLn Nothing
  let classes = genClassPaths ++ java_class_srcs
  when (not (null classes)) $
    createJar dflags' extras classes
  return ((if null classes then [] else [extras]) ++ o_files')
  where (java_srcs, non_java_srcs) = partition (isJavaishFilename . fst) srcs
        (java_class_srcs, java_source_srcs) = partition isJavaClassishFilename
                                              $ map fst java_srcs
        class_dirs = map takeDirectory java_class_srcs
```
is found in `ETA.Main.DriverPipeline` - it's where the `__extras.jar` gets built. Can you add the following debugging outputs:

```haskell
  ...
  print ("Classes", classes)
  when (not (null classes)) $
    createJar dflags' extras classes
  ...
```

Then, run `./cleaninstall.sh`. If it fails, follow the instructions above regarding modifying `shake/Build.hs` and run the `./cleaninstall.sh` script again and share the output.

If possible, see if you guys can fix this since it's difficult for me to figure out what's going on without being on your configurations.

**Comment by JulianZhang** [comment] 2017-05-15 04:05
@rahulmutt  I find why  you can't reproduce the issue , It not because macOS, it was because the charset. 
The `stderr` string in `runJavac` will different if the system charset is Chinese (I think other language should be the same problem).  The word "wrote " before "RegularFileObject" will change to local language. 

[stderr](https://gist.github.com/JulianZhang/b8d6fdde98f91c22e18e186b3bef2737)

I can try to fix it, but I think I need import MissingH for Data.List.Utils.

**Comment by rahulmutt** [comment] 2017-05-15 04:13
Great sleuthing @JulianZhang! But it does look like `RegularFileObject` stays the same so we should search for that. 

Which function do you need from `Data.List.Utils`? There are actually a lot of functions in `ETA.Utils.Util` you can use.

**Comment by JulianZhang** [comment] 2017-05-15 05:41
@rahulmutt you are right, we didn't need Data.List.Utils. I will create  pull request soon.

**Comment by rahulmutt** [comment] 2017-05-15 16:58
Should be fixed now.

**Closed by rahulmutt** 2017-05-15 16:58 UTC
Labels: bug
