### ISSUE TITLE
Corrupted String Output

### ISSUE THREAD

**Issue by dsorokin** [typelead/eta#672] opened 2018-02-21 06:34 UTC
Hi! 

When comparing Eta with GHC, I noticed that I received a corrupted string output like this:

```
  -- the current available countAê5¶¯0ë´WÒGi60¼3.[¾ ±&6Öö±ê­×wY÷çÙrÔÕÖíâ¡1Sgd«HÖ¡¡¦¶×#o4ìNqz!U=f§
  count­×wY÷çÙrÔÕÖíâ¡1Sgd«HÖ¡¡¦¶×#o4ìNqz!U=f§ = 0
```

although GHC returns:

```
  -- the current available count
  count = 0
```

The source test is located here (I'm the author of Aivika): https://github.com/dsorokin/aivika-gpss-test

By the way, when I increase the stop time (the spcStopTime parameter), I receive quite different estimation of the speed relative to GHC. I guess it could be related to the fact that GC in Haskell can be more optimal and fast than that one which is used in JVM. I extensively use continuations that produce a huge amount of short-living objects. But this is only an assumption.

Best regards,
David Sorokin

**Comment by jneira** [comment] 2018-02-21 10:32
Hi @dsorokin, it is good to see that awesome libs like aikiva are being tested with eta.
 I've clone your repo in windows and initially i could not able to run it cause `awm-random` was reading `/dev/urandom` to generate a random seed.
After patching awm-random locally to make it [use java](https://docs.oracle.com/javase/7/docs/api/java/security/SecureRandom.html#getSeed(int)) to get the seed i managed to run `aikiva-gpss-test` with this output:
```
Running aivika-gpss-test...
----------

-- simulation time
t = 1.0e7

-- Line
line:

  -- is the queue empty?
  queueNull = True

  -- the current queue content
  queueContent = 0

  -- the queue content statistics
  queueContentStats = { count = 10009, mean = 0.6419713491900471, std = 1.305698
7057392822, min = 0 (t = --0.0), max = 10 (t = 2920027.7305544894), t in [--0.0,
 9998647.780853195] }

  -- the number of enqueued transacts
  enqueueCount = 5004

  -- the number of zero entry enqueued transacts
  enqueueZeroEntryCount = 2456

  -- the wait time
  queueWaitTime = { count = 5004, mean = 1282.7428868805705, std = 2524.20190318
4826, min = --0.0, max = 18898.35166371148 }

  -- the wait time without zero entries
  queueNonZeroEntryWaitTime = { count = 2548, mean = 2519.170096526845, std = 30
65.868687565213, min = 0.3377572912722826, max = 18898.35166371148 }

  -- the average queue rate (= queue size / wait time)
  queueRate = 5.004676741971422e-4

-- Prof
prof:

  -- the current queue size
  queueCount = 0

  -- the queue size statistics
  queueCountStats = { count = 11371, mean = 0.7046684410221319, std = 1.34481392
07395233, min = 0 (t = --0.0), max = 11 (t = 2920425.749674708), t in [--0.0, 99
96952.921387823] }

  -- the total wait time
  totalWaitTime = 7044537.230086004

  -- the wait time
  waitTime = { count = 13127, mean = 536.6448716451562, std = 1669.3619966920817
, min = --0.0, max = 18898.35166371148 }

  -- the total holding time
  totalHoldingTime = 7122354.2588121565

  -- the holding time
  holdingTime = { count = 9989, mean = 713.0197476035777, std = 1017.69758357428
8, min = 6.121884100139141e-2, max = 10128.856661003083 }

  -- is the facility interrupted now?
  interrupted = False

  -- the current available count
  count = 0

  -- the available count statistics
  countStats = { count = 19980, mean = 0.28766825125583145, std = 0.452675632738
54633, min = 0 (t = 2246.628028442641), max = 1 (t = --0.0), t in [--0.0, 999864
7.780853195] }

  -- the current capture count
  captureCount = 9990

  -- the current utilisation count
  utilisationCount = 1

  -- the utilisation count statistics
  utilisationCountStats = { count = 19980, mean = 0.7123317487441685, std = 0.45
26756327385464, min = 0 (t = --0.0), max = 1 (t = 2246.628028442641), t in [--0.
0, 9998647.780853195] }
```
* The output seems to be fine. I think the difference could be the program versions used:
  * I am using eta built from source using master
  * My versions are:
     * eta: `The Eta Programming Language Compiler, Version 0.7.0b2, Git Revision 34a670d94e2
51d3811bcc9756c138ccdbd002e97`
     * etlas: `1.2.0.0`
  * I guess the error is caused by a incorrect String allocation, corrected with [this pr](https://github.com/typelead/eta/pull/654) so any later eta version should work

**Comment by dsorokin** [comment] 2018-02-21 10:35
Thanks for the reply! Then I will test it on Windows and Linux too.

I used macOS and Java 1.8:

```
$ uname -a
Darwin perseus.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by dsorokin** [comment] 2018-02-21 10:38
Also I used:

```
$ etlas --version
etlas version 1.2.0.0
compiled using version 2.1.0.0 of the etlas-cabal library 
$ etlas exec eta -- --version
Compiler for the Eta Programming Language, version 0.7.0b2
```

**Comment by dsorokin** [comment] 2018-02-21 10:40
Also I should add that I had one of the previous versions of etlas before installing the mentioned one. Probably, I should repeat from clear installation then.

**Comment by jneira** [comment] 2018-02-21 10:55
I am afraid that the actual version [0.7.0b2](https://github.com/typelead/eta/tree/0.7.0b2) doesnt contains the fix so you would have to build eta from source to get it, moreover: 
  * To make it work the actual master version, [this pr](https://github.com/typelead/eta/pull/673) should be merged
  * To make it work in windows the [patch for awm-random](https://github.com/typelead/eta-hackage/pull/74) should be merged in eta-hackage

**Comment by dsorokin** [comment] 2018-02-21 18:56
Thank you very much! I confirm that the issue has gone on macOS. My test works as expected. I hope it will work the same on Windows and Linux. Please close the issue if you consider it complete.

Best regards,
David Sorokin

**Comment by jneira** [comment] 2018-02-22 05:32
Great, close the issue then

**Closed by jneira** 2018-02-22 05:32 UTC
