### ISSUE TITLE
Getting started Method 1: Binary Installation is missing info on Eta

### ISSUE THREAD

**Issue by pasniak** [typelead/eta#503] opened 2017-09-07 12:57 UTC
How do I get the binary Eta?  I see

http://eta-lang.org/docs/html/getting-started.html

Method 1: Binary Installation
Eta Version: 0.0.9b1

**Comment by rahulmutt** [comment] 2017-09-07 13:05
If you scroll down, you should see links for each platform (highlighted in blue).

**Comment by rahulmutt** [comment] 2017-09-07 15:50
I apologise - I just understood your question. Etlas will download the binaries for you. We did it this way so that you can quickly switch between different versions of eta without messing with your path.

**Comment by pasniak** [comment] 2017-09-08 01:02
Okay thanks!  I am trying to set up Eta on a corporate Windows box, which might not have the usual stuff...

```
Attempting to download binaries...
Downloading the latest package lists from:
- hackage.haskell.org
- etlas.typelead.com
etlas: The program 'git' version >=1.8.5 is required but it could not be
found.
```

After I added GIT to path. 

```
c:\dev\eta-first>git --version
git version 1.9.0.msysgit.0

c:\dev\eta-first>etlas init
Discovering the installation paths for your Eta executables...
No existing installation found for 'eta'.
Attempting to download binaries...
Downloading the latest package lists from:
- hackage.haskell.org
- etlas.typelead.com
etlas: Could not read index. Did you call 'checkForUpdates'?
```

**Comment by rahulmutt** [comment] 2017-09-09 14:44
This looks related to #487.  

Can you clear out `%APPDATA%/Local/Roaming/etlas` and do `etlas init -v3` and share the output? It'll be long so you might want to share it as a Gist or on pastebin.

**Comment by pasniak** [comment] 2017-09-15 13:25
How do I provide proxy settings?

> Config file path source is default config file.
> Config file C:\Users\pasniewm\AppData\Roaming\etlas\config not found.
> Writing default configuration to
> C:\Users\pasniewm\AppData\Roaming\etlas\confi
> no user package environment file found at C:\dev\eta-first
> Discovering the installation paths for your Eta executables...
> No existing installation found for 'eta'.
> Attempting to download binaries...
> dieVerbatim: user error (etlas: 'C:\Program Files (x86)\Git\bin\curl.exe' exited with an error:
> curl: (7) Failed connect to objects-us-west-1.dream.io:80; No error

**Comment by rahulmutt** [comment] 2017-09-15 13:33
@jneira I remember you were working on this - what's the approach here?

**Comment by jneira** [comment] 2017-09-15 21:43
I am afraid i never tried to do a binary installation behind the proxy. Anyway i think etlas tries to use system proxy config and f.e. `etlas update` works for me in my win 7 env (but strangely not inside eta-build).
So i would check the values of http_proxy and https_proxy (curl uses win system proxy since 0.9.2), then i would try to execute the curl command with the same args that etlas (i think it should be printed by etlas with -v3). Maybe the proxy is banning that host or something.

**Comment by jneira** [comment] 2017-09-19 08:36
I try the binary installation behind a proxy and it has failed for me, but with other error (like #487):
```
D:\>etlas init -v3
no user package environment file found at D:\
Discovering the installation paths for your Eta executables...
No existing installation found for 'eta'.
Attempting to download binaries...
Downloading executable 'eta'...
Downloading executable 'eta-pkg'...
Selected eta-0.0.9b1.
Downloading [binary] rts-0.1.0.0...
Downloading [binary] ghc-prim-0.4.0.0...
Downloading [binary] integer-0.5.1.0...
Downloading [binary] base-4.8.2.0...
Downloading [binary] ghc-boot-th-8.0.2...
Downloading [binary] array-0.5.2.0...
Downloading [binary] deepseq-1.4.3.0...
Downloading [binary] pretty-1.1.3.5...
Downloading [binary] template-haskell-2.11.1.0...
etlas: Cannot find the program 'eta'. User-specified path
'C:\Users\user\AppData\Roaming\etlas\binaries\6899fa2dcac85d20d417-8f2e61d843ea88
e4f30ab3f81ca0e396.ssl.cf5.rackcdn.com\eta-0.0.9.1\binaries\x86_64-windows\eta.e
xe'
does not refer to an executable and the program is not on the system path.
```
* Without curl in path
* The etlas directory structure is created (included `binaries\x86_64-windows`) but there is no executables in.
* No error about the missing download 
* Tried with basic console and powershell

**Comment by rahulmutt** [comment] 2017-09-19 15:01
This is a serious issue indeed. I remember catching exceptions on HTTP failures but it should display proper error messages. @jneira Can you try adding debugging outputs to `downloadPrograms` in `Distribution.Client.BinaryUtils`, especially checking the existence of the downloaded file and dieing if not present after downloading?

**Comment by pasniak** [comment] 2017-09-20 08:50
I tried to set http_proxy and https_proxy env var to working proxy values and I got curl process waiting/hanging.  I then tried to run curl command issued with --verbose.  (I removed IP address info):

```
c:\dev\eta-first>"C:\Program Files (x86)\Git\bin\curl.exe" "http://objects-us-west-1.dream.io/hackage-mirror/01-index.tar.gz" "--output" "c:\Temp\transportAdapterGet1971819895" "--location" "--write-out" "%{http_code}" "--user-agent" "etlas/1.0.2.0 (windows; x86_64)" "--silent" "--show-error" "--dum
p-header" "c:\Temp\curl-headers544721726.txt" "--header" "Cache-Control: no-transform" --verbose
* Adding handle: conn: 0x21a2778
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x21a2778) send_pipe: 1, recv_pipe: 0
* About to connect() to proxy primary-proxy.<cut> port 8080 (#0)
*   Trying 10.##.##.##...
* Connected to primary-proxy.<cut> port 8080 (#0)
> GET http://objects-us-west-1.dream.io/hackage-mirror/01-index.tar.gz HTTP/1.1
> User-Agent: etlas/1.0.2.0 (windows; x86_64)
> Host: objects-us-west-1.dream.io
> Accept: */*
> Proxy-Connection: Keep-Alive
> Cache-Control: no-transform
>  
< HTTP/1.1 200 OK
< Content-Length: 62103831
< Accept-Ranges: bytes
< Last-Modified: Tue, 19 Sep 2017 13:49:01 GMT
< ETag: "9fee9b41d5ebaeadd9450f085aa2021b"
< x-amz-request-id: tx0000000000000006b48f9-0059c13dd2-1926dc93-default
< Content-Type: application/x-gzip
< Date: Tue, 19 Sep 2017 15:54:58 GMT
< Proxy-Connection: Keep-Alive
< Connection: Keep-Alive
< Age: 584
<  
{ [data not shown]
* Recv failure: Connection was reset
* Closing connection 0
200curl: (56) Recv failure: Connection was reset
```

**Comment by jneira** [comment] 2017-09-20 10:23
* I notice that download package index from scratch is very slow: several minutes for me (with etlas init hanged in `Updating binary package index.`). But it finally completes
* Curl http transport (default one) seems to need the http_proxy env var set (it seems to hangs forever without it)
* `etlas update -v3` gives me this error about downloading binaries (i've added some new traces to etlas):
```
In downloadURI
"D:\\curl.exe" "https://6899fa2dcac85d20d417-8f2e61d843ea88
e4f30ab3f81ca0e396.ssl.cf5.rackcdn.com/eta-0.0.9.1/binaries/i386-windows/index"
"--output" "C:\Users\user\AppData\Roaming\etlas\binaries\6899fa2dcac85d20d417-8f2
e61d843ea88e4f30ab3f81ca0e396.ssl.cf5.rackcdn.com\eta-0.0.9.1\binaries\i386-wind
ows\index2328116827" "--location" "--write-out" "%{http_code}" "--user-agent" "e
tlas/1.0.2.0 (windows; i386)" "--silent" "--show-error" "--dump-header" "C:\User
s\user\AppData\Roaming\etlas\binaries\6899fa2dcac85d20d417-8f2e61d843ea88e4f30ab3
f81ca0e396.ssl.cf5.rackcdn.com\eta-0.0.9.1\binaries\i386-windows\curl-headers996
1491.txt"
Download result: (404,Nothing)
Error downloading file
[eta-0.0.9b1] Unable to download binary index file -
https://6899fa2dcac85d20d417-8f2e61d843ea88e4f30ab3f81ca0e396.ssl.cf5.rackcdn.co
m/eta-0.0.9.1/binaries/i386-windows/index
```
full log [here](https://gist.github.com/jneira/3f6103a3c0be6003c1d3b2eb525f0b52)

**Comment by jneira** [comment] 2017-09-21 08:48
@pasniak hi, when i try `etlas update -v3` (after deleting `%APPDATA%/Local/Roaming/etlas`) it chose another mirror for download `01-index.tar.gz`:
```cmd
Trying to locate mirrors via DNS for initial bootstrap of secure repository
'http://hackage.haskell.org/' ...
Searching for nslookup in path.
Found nslookup at C:\windows\system32\nslookup.exe
"C:\windows\system32\nslookup.exe" "-query=TXT" "_mirrors.hackage.haskell.org"
located 2 mirrors for http://hackage.haskell.org/ :
- http://hackage.fpcomplete.com/
- http://objects-us-west-1.dream.io/hackage-mirror/
Selected mirror http://hackage.haskell.org/
....
Cannot update index (no local copy)
Downloading index
Updating binary package index.
"D:\curl.exe" "http://hackage.haskell.org/01-index.tar.gz"
 "--output" "C:\TEMP\transportAdapterGet2328116827" "--location" "--write-out" "
%{http_code}" "--user-agent" "etlas/1.0.2.0 (windows; i386)" "--silent" "--show-
error" "--dump-header" "C:\TEMP\curl-headers9961491.txt" "--header" "Cache-Contr
ol: no-transform"
creating
```
It seems the `http://objects-us-west-1.dream.io/hackage-mirror/` is extremely slow (if i try to download in browser it shows an initial delay of 10 min) and/or curl can't download the file from it for some reason.
Could you share the full output of `etlas update -v3` (after deleting `%APPDATA%/Local/Roaming/etlas`)?

**Comment by jneira** [comment] 2017-09-25 22:14
* It turns out that the error downloading the eta executable was caused by my etlas built from source for testing, for 32 bits instead 64. It tried to download the 32.bit eta version that is not in the server
* Testing in win 10 with the correct arch for etlas, it gets the executable correctly:
```
Searching for eta in path.
Cannot find eta on the path
Discovering the installation paths for your Eta executables...
Searching for eta in path.
Cannot find eta on the path
No existing installation found for 'eta'.
Attempting to download binaries...
Searching for curl in path.
Found curl at
C:\Users\Javier\dev\app\curl_7_53_1_openssl_nghttp2_x64\bin\curl.exe
Searching for powershell in path.
Found powershell at C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
Searching for wget in path.
Cannot find wget on the path
Selected http transport implementation: curl
Downloading executable 'eta'...
"C:\Users\Javier\dev\app\curl_7_53_1_openssl_nghttp2_x64\bin\curl.exe" "https://6899fa2dcac85d20d417-8f2e61d843ea88e4f30ab3f81ca0e396.ssl.cf5.rackcdn.com/eta-0.0.9.1/binaries/x86_64-windows/eta.exe" "--output" "C:\Users\Javier\AppData\Roaming\etlas\binaries\6899fa2dcac85d20d417-8f2e61d843ea88e4f30ab3f81ca0e396.ssl.cf5.rackcdn.com\eta-0.0.9.1\binaries\x86_64-windows\eta4118467.exe" "--location" "--write-out" "%{http_code}" "--user-agent" "etlas/1.0.2.0 (windows; x86_64)" "--silent" "--show-error" "--dump-header" "C:\Users\Javier\AppData\Roaming\etlas\binaries\6899fa2dcac85d20d417-8f2e61d843ea88e4f30ab3f81ca0e396.ssl.cf5.rackcdn.com\eta-0.0.9.1\binaries\x86_64-windows\curl-headers633426500.txt"
Downloaded to
C:\Users\Javier\AppData\Roaming\etlas\binaries\6899fa2dcac85d20d417-8f2e61d843ea88e4f30ab3f81ca0e396.ssl.cf5.rackcdn.com\eta-0.0.9.1\binaries\x86_64-windows\eta.exe
```

**Comment by rahulmutt** [comment] 2017-09-26 13:10
@jneira So it it working behind a proxy on Windows?

**Comment by jneira** [comment] 2017-09-26 19:33
@rahulmutt yeah, i dont test it completely with full debug cause in my case the antivirus is blocking the copy of the downloaded executable to its final dir. But the download (using the 64 bit version) works fine

**Comment by pasniak** [comment] 2017-09-27 10:10
I tried the `atlas update -v3`. I don't have the stdout but I observed 3 websites hit, of which 2 were blocked (I tried the URLs of `index-01.gz` or sth alike, in my Chrome). The `fpcomplete.com` download in Chrome seemed to progress through to ~54MB but an error saving file occurred.  I guess I'll try to build from source...  Thanks for your help!

**Comment by rahulmutt** [comment] 2017-09-27 13:36
Even if you build from source, not being able to download `index-01.gz` (which stores the package index) will disable you from installing new packages, so you'll be stuck with an eta installation that just has the standard library.

You mentioned an error with `fpcomplete.com` download - can you share it?

**Comment by jneira** [comment] 2019-01-22 21:54
I think we can close this one

**Closed by jneira** 2019-01-22 21:54 UTC
