### ISSUE TITLE
[FFI] Exported functions that make use of STDOUT do not print anything from Java

### ISSUE THREAD

**Issue by NickSeagull** [typelead/eta#710] opened 2018-03-23 17:15 UTC
I'm trying to export a function like:

```haskell
foreign export java
 foo :: IO ()
foo = putStrLn "Hi"
```

and then call it from Java with

```java
import my_project.Lib;

public class Utils {
    public static void main(String args[]) throws Exception {
        System.out.println("======== RUNNING  ===============");
        Lib.foo();
        System.out.println("=================================");
    }
}
```

The `Hi` doesnt get printed.

By suggestion of @rahulmutt , I've changed the definition of `foo` to:

```haskell
foo = putStrLn "HI" >> hFlush stdout
```

But still, it doesn't get printed.

**Comment by jneira** [comment] 2018-05-14 06:39
Hi, i've reproduced the issue in [this branch of my eta-test project](https://github.com/jneira/eta-test/tree/print-ffi). Then i've decompiled the project class files and compiled again with javac and the output is correct, so i think the bug is related with the jvm bytecode generated by eta.
The decompiled java files and recompiled with javac class ones is [in this jar](https://github.com/jneira/eta-test/blob/print-ffi/jar/eta-test.jar). You have to add the boot eta libs in the classpath to run it and test the output, f.e.:
```
> java -cp .\rts-0.1.0.0-5Dj4qf1Wx9cCeYbpni5T1w.jar;.\ghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE.jar;.\integer-0.5.1.0-ACyqTmAMUMGGvisLFeQbAm.jar;.\ghc-prim-0.4.0.0-Jhi6UgHuZdoBZWUpVo3WKE.jar;.\base-4.8.2.0-IPFDtZjmEfh5tPXF10v5hF.jar;eta-test.jar Utils
```
So afaik comparing the jvm bytecode between the eta build and the jar we could identify the cause.

**Comment by jneira** [comment] 2018-06-18 09:29
Hi, the problem was simpler than expected by me:
* Anf ffi export should have `@static` int the `[export string]` to generate static methods in the class module. Without it it generates instance method not callable from java cause the class module has no constructors
* With 
```
foreign export java
 foo :: IO ()
foo = putStrLn "Hi"
```
* Eta generate this method in the class module:
```
public static eta.runtime.stg.Closure foo()
  {
    return foo.INSTANCE;
  }
public void foo()
  {
    Runtime.evalIO(new Ap2Upd(base.ghc.TopHandler.runIO(), new Ap1Upd($fe_foo())));
  }
```
* That is, there is a static method that returns the internal closure to be evaluated and no the expected code (in the instance method)
* If you replace the code with
```
foreign export java "@static eta_test.Lib.exportedFoo" foo :: IO ()
foo = putStrLn "Hi"
```
* `Lib.exportedFoo();` works as expected
* Note that the name of the exported method must be differente of the eta function cause with the same name eta generates:
```
public static Closure foo()
  {
    return bar.INSTANCE;
  }
public static void foo()
  {
    Runtime.evalJava(null, new Ap2Upd(base.java.TopHandler.runJava(), new Ap1Upd($fe_foo())));
  }
```
* And the code compiles but only the first one is executed

**Comment by rahulmutt** [comment] 2018-06-18 11:11
@jneira Great analysis. I think all this will be fixed with better typechecking for foreign exportation declarations which is going to be done soon.

**Comment by jneira** [comment] 2018-07-03 08:17
I think with the changes in docs of #782 and the new issue to avoid ill defined ffi exports #787 we can close this one.

**Closed by jneira** 2018-07-03 08:17 UTC
Labels: bug, ffi
