### ISSUE TITLE
It failed to build eta example project in ubuntu on windows 10 WSL

### ISSUE THREAD

**Issue by flyfish30** [typelead/eta#537] opened 2017-10-12 02:34 UTC
I install the ubuntu on windows 10 by WSL, and then successfully install the etlas by follow the guide line in eta-lang.org. But after I use etlas init to initialize a example project, it is failed to build a executable jar for this project.

The Main.hs is show bellow:
module Main where

main :: IO ()
main = putStrLn "Hello, Eta!"

The output of etlas build -v command is difference with this command run in original ubuntu system. The detail information of the build process is show bellow:
parker@LAPTOP-OIKP6CEQ:/mnt/d/Work/etalang/examples$ etlas clean
cleaning...
parker@LAPTOP-OIKP6CEQ:/mnt/d/Work/etalang/examples$ etlas configure --enable-uberjar-mode
Resolving dependencies...
Configuring examples-0.1.0.0...
parker@LAPTOP-OIKP6CEQ:/mnt/d/Work/etalang/examples$ etlas build -v
Using internal setup method with build-type Simple and args:
["build","--verbose=2","--builddir=dist","--jobs=4"]
Component build order: executable 'examples'
/home/parker/.etlas/binaries/6899fa2dcac85d20d417-8f2e61d843ea88e4f30ab3f81ca0e396.ssl.cf5.rackcdn.com/eta-0.0.9.1/binaries/x86_64-linux/eta-pkg init dist/package.conf.inplace
creating dist/build/examples
creating dist/build/examples/autogen
creating dist/build/examples/autogen
Preprocessing executable 'examples' for examples-0.1.0.0..
Building executable 'examples' for examples-0.1.0.0..
creating dist/build/examples/examples-tmp
/home/parker/.etlas/binaries/6899fa2dcac85d20d417-8f2e61d843ea88e4f30ab3f81ca0e396.ssl.cf5.rackcdn.com/eta-0.0.9.1/binaries/x86_64-linux/eta --make -fbuilding-cabal-package -O2 -j4 -outputdir dist/build/examples/examples-tmp -odir dist/build/examples/examples-tmp -hidir dist/build/examples/examples-tmp -stubdir dist/build/examples/examples-tmp -i -idist/build/examples/examples-tmp -isrc -idist/build/examples/autogen -idist/build/global-autogen -Idist/build/examples/autogen -Idist/build/global-autogen -Idist/build/examples/examples-tmp -optP-include -optPdist/build/examples/autogen/cabal_macros.h -hide-all-packages -package-db dist/package.conf.inplace -XHaskell2010 src/Main.hs -o dist/build/examples/examples.jar -pgmjavac /usr/bin/javac -cp ''

src/Main.hs:1:1:
    Could not find module ‘Prelude’
    Use -v to see a list of the files searched for.

**Comment by rahulmutt** [comment] 2017-10-13 15:43
Hi @flyfish30, can you share the exact steps you used to perform installation of Eta via WSL and installation of Etlas? You actually don't need to install *both*.

**Comment by rahulmutt** [comment] 2017-10-30 10:34
@flyfish30 Any updates on this?

**Comment by jneira** [comment] 2018-05-21 23:26
closing cause we are not able to reproduce: @flyfish30, feel free to reopen if you continue having the error

**Closed by jneira** 2018-05-21 23:26 UTC
