### ISSUE TITLE
REPL uses CPU while doing nothing

### ISSUE THREAD

**Issue by borkdude** [typelead/eta#862] opened 2018-08-23 06:51 UTC
## Description
I have tried the eta-scotty-example https://github.com/Jyothsnasrinivas/eta-scotty-example in the `etlas repl`.
When the REPL is showing a prompt and not doing anything else, the CPU usage for a java process goes up to 150% on my Macbook Air.

## Expected Behavior
I expect the REPL to not use much resources when idling.

## Actual Behavior
150% CPU usage on a Macbook Air.

## Steps to Reproduce
1. git clone https://github.com/Jyothsnasrinivas/eta-scotty-example
2. cd eta-scotty-example
3. etlas repl
4. wait for the prompt

## Your Environment
* Current Eta & Etlas version:

etlas version 1.5.0.0
compiled using version 2.1.0.0 of the etlas-cabal library
 Eta REPL v0.8.6b1

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

* Operating System and version:
MacOS El Capitan 10.11.6

**Comment by rahulmutt** [comment] 2018-08-24 08:59
This is a duplicate of #839. This will be fixed in 0.8.6b2 which will be released within the next week.

**Closed by rahulmutt** 2018-08-24 08:59 UTC
